version: '3'
services:
    mongodb:
        image: mongo
        container_name: vidya-mongodb
        volumes:
            - ../deployment/vidya/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        # restart: always
        networks:
            - default
    web:
        build: .
        image: vidya-image
        container_name: vidya-web
        volumes:
            - .:/app
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8080:9000
        links:
            - mongodb
        networks:
            - default
        # restart: always
        environment:
            FLASK_ENV: production
            VIDYA_SETTINGS: /app/vidya-development.cfg
        command: /app/scripts/vidya-uwsgi.sh
    checker:
        build: .
        image: vidya-image
        container_name: vidya-checker
        volumes:
            - .:/app
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - mongodb
        networks:
            - default
        # restart: always
        environment:
            VIDYA_SETTINGS: /app/vidya-development.cfg
        command: vidya-checker

networks:
    default:
        driver: bridge
      
